SRCS	=	main.cpp Weapon.cpp HumanA.cpp HumanB.cpp

OBJS	=	${SRCS:.cpp=.o}

NAME = UnnecessaryViolence

HEADER = Weapon.hpp HumanA.hpp HumanB.hpp

CXX = clang++

RM = rm -f

CPPFLAGS = -Wall -Wextra -Werror -std=c++98

.PHONY: all clean fclean re

.cpp.o:
			${CXX} ${CPPFLAGS} -c $< -o $@

all:		${NAME}

${NAME}:	${OBJS} ${HEADER}
			@${CXX} ${CPPFLAGC} -o ${NAME} ${OBJS}

clean:
			@${RM} ${OBJS}

fclean:		clean
			@${RM} ${NAME}

re:			fclean all